<?php

namespace BonPlan\DealsBundle\Repository;

/**
 * DealsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealsRepository extends \Doctrine\ORM\EntityRepository
{
}
